---
abstract: 'Use semantic version numbers'
author:
  - 'David E. Wheeler <david@kineticode.com>'
build_requires:
  Module::Build: 0.30
  Test::More: 0.88
configure_requires:
  Module::Build: 0.30
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SemVer
provides:
  SemVer:
    file: lib/SemVer.pm
    version: v0.3.0
recommends:
  Test::Pod: 1.41
  Test::Pod::Coverage: 1.06
requires:
  perl: 5.008001
  version: 0.82
resources:
  bugtracker: http://github.com/theory/semver/issues/
  homepage: http://search.cpan.org/dist/SemVer/
  license: http://dev.perl.org/licenses/
  repository: http://github.com/theory/semver/tree/
version: v0.3.0
